version: '3.8'
name: vaultr-communication

services:

  vaultr-communication:
    container_name: vaultr-communication
    build:
      context: .
      dockerfile: Dockerfile
    image: vaultr-communication
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - vaultr-net

networks:
  vaultr-net:
    name: vaultr-net
    driver: bridge
    external: true